source_config: # PostgreSQL
  dialect: postgresql
  driver: PostgreSQL Unicode
  connection:
    host: localhost
    port: 5432
    database: test_db
    username: postgres
    password: sql
    schema:

source:
  dialect: mssql+pyodbc
  driver: ODBC Driver 17 for SQL Server
  connection:
    host: localhost
    database: prac
    username: lin
    password: sql

staging: # PostgreSQL
  dialect: postgresql
  driver:  PostgreSQL Unicode
  connection:
    host: localhost
    port: 5432
    database: examplewh
    username: postgres
    password: sql
    schema: 

dwh: # PostgreSQL
  dialect: postgresql
  driver:  PostgreSQL Unicode
  connection:
    host: localhost
    port: 5432
    database: postgres
    username: postgres
    password: sql
    schema: 

clickhouse: # http port for sqlalchemy
  dialect: clickhouse
  driver: clickhouse+native
  connection:
    host: localhost
    port: 8123
    database: my_database
    username: admin
    password: admin

clickhouse-tcp: # tcp port for clickhouse_driver
  dialect: clickhouse
  driver: 
  connection:
    host: 
    port: 9000
    database: 
    username: 
    password: 